<?php
    $this->headTitle('Create Crawl');
?>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Welcome to Crawler Crawly') ?></h3>
            </div>
            <div class="panel-body">
                <?php

                    $form->setAttribute('action', $this->url('create', array('action' => 'create')));
                    $form->prepare();

                    echo $this->form()->openTag($form);
                    echo $this->formRow($form->get('url'));
                    echo $this->formSubmit($form->get('submit'));
                    echo $this->form()->closeTag();

                ?>
            </div>
        </div>
    </div>
</div>
