<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Your crawls:') ?></h3>
            </div>
            <div class="panel-body">
                <?php
                    foreach ($crawls as $crawl)
                    {
                        ?>
                        <div class="col-md-12">
                            <div class="col-md-4">
                                <?php
                                    echo $crawl->url;
                                ?>
                            </div>
                            <div class="col-md-4">
                                <?php
                                    echo $crawl->finding;
                                ?>
                            </div>
                            <div class="col-md-2">
                                <?php
                                    echo $crawl->date;
                                ?>
                            </div>
                            <div class="col-md-2">
                                <a href="<?php $this->url('delete') ?>">
                                <?php
                                    echo $this->translate('delete');
                                ?></a>
                            </div>
                        </div>
                        <?php
                    }
                ?>
            </div>
        </div>
    </div>
</div>
